// <auto-generated />
using ContactsListDBWoodburn.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContactsListDBWoodburn.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20210212061434_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ContactsListDBWoodburn.Models.Comment", b =>
                {
                    b.Property<string>("CommentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = "A",
                            Name = "Family"
                        },
                        new
                        {
                            CommentId = "B",
                            Name = "Work"
                        },
                        new
                        {
                            CommentId = "C",
                            Name = "Friend"
                        },
                        new
                        {
                            CommentId = "D",
                            Name = "Technical"
                        },
                        new
                        {
                            CommentId = "E",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ContactsListDBWoodburn.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(70)")
                        .HasMaxLength(70);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.HasIndex("CommentId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 4,
                            Address = "100 Main Avenue",
                            CommentId = "D",
                            Name = "Casablanca",
                            PhoneNumber = "555-5555"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "100 Main Avenue",
                            CommentId = "A",
                            Name = "Wonder Woman",
                            PhoneNumber = "555-5555"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "100 Main Avenue",
                            CommentId = "E",
                            Name = "Moonstruck",
                            PhoneNumber = "555-5555"
                        });
                });

            modelBuilder.Entity("ContactsListDBWoodburn.Models.Contact", b =>
                {
                    b.HasOne("ContactsListDBWoodburn.Models.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
